name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Setup:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Restore NuGet 
        run: |
          nuget restore
    
    BuildAndroidApp:
      runs-on: macos-latest

      needs: Setup

      steps:
      - uses: actions/checkout@v1

      - name: Build Android App
        run: |        
          AndroidProject=`find . -name AsyncCommandSample.Android.csproj`
          echo $AndroidProject   

          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll $AndroidProject /verbosity:normal /p:Configuration=Release     
  
    RunUnitTests:
      runs-on: macos-latest

      needs: Setup

      steps:
      - uses: actions/checkout@v1

      steps:
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name AsyncCommandSample.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject