name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Setup:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Restore NuGet 
        run: |
          nuget restore
    
    BuildAndroidApp:
      runs-on: macos-latest

      needs: Setup

      steps:
      - name: Build Android App
        run: |           
          echo Current Directory: $(pwd)
          ech ls: $(ls -a)

          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ../AsyncCommandSample.Android/AsyncCommandSample.Android.csproj /verbosity:normal /p:Configuration=Release     
          
      # - name: Build iOS App
      #   run: |                    
      #     mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./GitTrends.iOS/GitTrends.iOS.csproj /verbosity:normal /p:Configuration=Debug /p:Platform=iPhoneSimulator
  
    RunUnitTests:
      runs-on: macos-latest

      needs: Setup

      steps:
      - name: Run Unit Tests
        run: |   
          echo Current Directory: $(pwd)
          ech ls: $(ls -a)

          UnitTestProject=`find .. -name AsyncCommandSample.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject