name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:    
    BuildAndroidApp:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet 
        run: |
          AndroidProject=`find . -name AsyncCommandSample.Android.csproj`
          echo $AndroidProject

          XamarinFormsProject=`find . -name AsyncCommandSample.csproj`
          echo $XamarinFormsProject  

          nuget restore $AndroidProject
          nuget restore $XamarinFormsProject

      - name: Build Android App
        run: |        
          AndroidProject=`find . -name AsyncCommandSample.Android.csproj`
          echo $AndroidProject   

          msbuild $AndroidProject /verbosity:normal /p:Configuration=Release     
  
    RunUnitTests:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v3
      
      - name: Setup v8.0
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '8.0.x'

      - name: Run Unit Tests
        run: 'dotnet test  -c Release AsyncCommandSample.UnitTests/AsyncCommandSample.UnitTests.csproj'
